# Generated by Django 5.1.4 on 2025-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_remove_userprofile_role_userprofile_extra_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='extra_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Librarian', 'Librarian'), ('Member', 'Member')], default='Member', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
