# Generated by Django 5.1.4 on 2025-01-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_book_publication_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(default=2023),
        ),
    ]
